spring:
  application:
    name: msvc-courses
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres14:5432}/${DB_DATABASE:msvc_courses}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: ${PORT:8002}

logging:
  level:
    org:
      hibernate:
        SQL: debug
  file:
    path: /app/logs

msvc:
  users:
    url: ${USERS_URL:msvc-users:8001/api/v1/users}