apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-users
data:
  lb_auth_issuer_uri: http://127.0.0.1:64309
  lb_users_uri: http://127.0.0.1:64304
  port: "8001"
  db_host: mysql8:3306
  db_name: msvc_users
  #  db_username: root
  #  db_password: sasa
  courses_url: msvc-courses:8002
  application.yml: |-
    config:
      text: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      text: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: pro
    config:
      text: Configurando ambiente de produccion

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-courses
data:
  port: "8002"
  db_host: postgres14:5432
  db_name: msvc_courses
  #  db_username: postgres
  #  db_password: sasa
  users_url: msvc-users:8001