apiVersion: v1
kind: Secret
metadata:
  name: msvc-users
type: Opaque
data:
  db_username: cm9vdA==
  db_password: c2FzYQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-courses
type: Opaque
data:
  db_username: cG9zdGdyZXM=
  db_password: c2FzYQ==