spring:
  application:
    name: msvc-users
  datasource:
    url: jdbc:mysql://mysql8:3306/msvc_users?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

server:
  port: 8001

logging:
  level:
    org:
      hibernate:
        SQL: debug
  file:
    path: /app/logs