spring:
  application:
    name: msvc-users
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql8:3306}/${DB_DATABASE:msvc_users}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

server:
  port: ${PORT:8001}

logging:
  level:
    org:
      hibernate:
        SQL: debug
  file:
    path: /app/logs

msvc:
  courses:
    url: ${COURSES_URL:msvc-courses:8002/api/v1/courses}