spring:
  profiles:
    active: pro
  application:
    name: msvc-users
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql8:3306}/${DB_DATABASE:msvc_users}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sasa}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9000}
      client:
        registration:
          msvc-users-client:
            provider: spring
            client-id: "users-client"
            client-secret: "12345"
            authorization-grant-type: authorization_code
            redirect-uri: ${LB_USERS_URI:http://127.0.0.1:8001}/authorized
            scope: READ
            client-name: msvc-users-client
        provider:
          spring:
            issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9000}

server:
  port: ${PORT:8001}

logging:
  level:
    org:
      hibernate:
        SQL: debug
  file:
    path: /app/logs

msvc:
  courses:
    url: ${COURSES_URL:msvc-courses:8002}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true